# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8509f5a62ca69a04990f1f9dfc2d25e74de15b91cc473c9b56e0ae129e62662f0f4f033168ceb033c01315567959d3474343bb898e783fca44ee7fd5a9703f41

test:
  secret_key_base: d47d6aef727aebc3e42a615ad36a3089d43abe54ead3941ee428b1f8cdb440042df613fc1e3c1a2c1974d26bc26b1dfbba96544452a9f4e7f88b0b0375d23bd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
